version: '2'

services:
  es-master:
    build: elasticsearch/
    ports:
      - "127.0.0.1:9200:9200"
    expose:
      - "9200"
      - "9300"
    environment:
      BM_ES_NODE_NAME: "es-master"
      ES_JAVA_OPTS: "-Xms250m -Xmx250m"
      BM_ES_MASTER: "true"
      BM_ES_DATA: "false"
    volumes:
      - ./elasticsearch/config:/usr/share/elasticsearch/config
    networks:
      - docker_elk
  es-data-1:
    build: elasticsearch/
    expose:
      - "9200"
      - "9300"
    environment:
      BM_ES_NODE_NAME: "es-data-1"
      ES_JAVA_OPTS: "-Xms8g -Xmx8g"
      BM_ES_MASTER: "false"
      BM_ES_DATA: "true"
    networks:
      - docker_elk
    links:
      - es-master:es-master
    depends_on:
      - es-master
    volumes:
      - ./elasticsearch/config:/usr/share/elasticsearch/config
      - /var/honeygrove/cim-data/data-1:/usr/share/elasticsearch/data
  es-data-2:
    build: elasticsearch/
    expose:
      - "9200"
      - "9300"
    environment:
      BM_ES_NODE_NAME: "es-data-2"
      ES_JAVA_OPTS: "-Xms8g -Xmx8g"
      BM_ES_MASTER: "false"
      BM_ES_DATA: "true"
    networks:
      - docker_elk
    volumes:
      - ./elasticsearch/config:/usr/share/elasticsearch/config
      - /var/honeygrove/cim-data/data-2:/usr/share/elasticsearch/data
    links:
      - es-master:es-master
    depends_on:
      - es-master
#  logstash:
#    build: logstash/
#    command: -f /etc/logstash/conf.d/
#    volumes:
#      - ./logstash/config:/etc/logstash/conf.d/
#      - /var/honeygrove/log:/var/honeygrove/log
#      - /var/honeygrove/log/logstash:/var/log/logstash
#    networks:
#      - docker_elk
#    depends_on:
#      - es-master
#    links:
#      - es-master:elasticsearch
  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/opt/kibana/config/
    ports:
      - "127.0.0.1:5601:5601"
    networks:
      - docker_elk
    depends_on:
      - es-master
    links:
      - es-master:elasticsearch

networks:
  docker_elk:
    driver: bridge
